### ISSUE TITLE
Add option to fine tune selected expansions on a 'per card' basis

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#112]
**Is your feature request related to a problem? Please describe.**
It might be useful for some users to pick exactly which cards the randomizers will include

**Describe the solution you'd like**
Add a button to each set which toggles a sublist showing all of its cards also with a checkbox.
Clicking on a card opens up a card preview containing **cost**, **type** and **text** of the card.

**Comment by on3iro** [comment]
## TODO
* [ ] Implement store for each entity type (mages, nemeses, cards)
* [ ] Use selected entities instead of current selection
* [ ] Add further information to entities (difficulty, keywords etc.)
* [ ] Styling
