### ISSUE TITLE
Add creation of custom market setups

### ISSUE THREAD

**Issue by on3iro** [on3iro/aeons-end-randomizer#21]
## TODOs

* [x] Add supply selection to settings
* [x] Add custom supply tab with checkboxlist
* [x] Add `addSupply`-button
* [x] Operations: 
    * [x] `Add` -> `isNew: true`, `isDirty: true`
        * [x] Automatic ID creation
    * [x] `Edit` -> `isNew: false`, `isDiry: true`
         * [x] Name Input
         * [x] `addCard`:
            * [x] Type, operation, threshold/values, cost
    * [x] `Save`
    * [x] `Cancel`
    * [x] `Delete`
* [x] Manage edit in local component state and only commit changes to redux on save
* [x] Show supply (some kind of Preview)
* [x] save custom supplys to indexedDB
* [x] fetch custom supplys and setup config
* [x] Read from selection
* [x] Fix bug that causes to evaluate supply order wrong (e.g. relic is first blueprint, but shown as last in supply)
* [x] Styling

**Comment by on3iro** [comment]
@jannydiamond It would be awesome If you could do some styling when I am done with implementing this. I will just reference this issue in the PR, but won't close it upon merging.  That way you can continue using this issue as reference as well.
We will close it, as soon as styling has been finished.

**Comment by on3iro** [comment]
@jannydiamond the basic feature is merged -> you can start styling whenever you are read ;)

**Comment by jannydiamond** [comment]
@on3iro alright, i'll have a look at it :)
